use std::rc::Rc;

pub type Name = Rc<str>;

pub fn name(s: &str) -> Name {
    Rc::from(s)
}

pub type Index = usize;
pub type Level = usize;

/// Surface syntax produced by the parser.
///
/// Named binders, sugar like `A -> B` and `A * B`, and unresolved
/// identifiers. Elaborated into [`Tm`] (Pujet-Tabareau call this the
/// "user syntax" before scope resolution).
#[derive(Clone, Debug)]
pub enum Raw {
    /// $x$ -- free or bound name, resolved during elaboration.
    Var(Name),
    /// $\lambda x_1\, \ldots\, x_n.\, t$ -- multi-binder lambda (sugar).
    Lam(Vec<Name>, Box<Raw>),
    /// $t\, u$ -- application.
    App(Box<Raw>, Box<Raw>),
    /// $\Pi (x_1\, \ldots\, x_n : A).\, B$ -- dependent function type.
    Pi(Vec<Name>, Box<Raw>, Box<Raw>),
    /// $A \to B$ -- non-dependent arrow, desugars to $\Pi (\_ : A).\, B$.
    Arrow(Box<Raw>, Box<Raw>),
    /// $\Sigma (x_1\, \ldots\, x_n : A).\, B$ -- dependent pair type.
    Sigma(Vec<Name>, Box<Raw>, Box<Raw>),
    /// $A \times B$ -- non-dependent product, desugars to $\Sigma (\_ : A).\, B$.
    Prod(Box<Raw>, Box<Raw>),
    /// $(a, b)$ -- pair introduction.
    Pair(Box<Raw>, Box<Raw>),
    /// $\pi_1\, t$ -- first projection.
    Fst(Box<Raw>),
    /// $\pi_2\, t$ -- second projection.
    Snd(Box<Raw>),
    /// $\mathcal{U}$ -- the universe (called `Type` in the surface, written
    /// $\square$ in Pujet-Tabareau's typing rules).
    U,
    /// $\mathbb{N}$ -- natural numbers.
    Nat,
    /// $0$ -- zero, the base constructor of $\mathbb{N}$.
    Zero,
    /// Numeric literal $n$, sugar for $\mathsf{S}^n\, 0$.
    NumLit(u64),
    /// $\mathsf{S}\, n$ -- successor.
    Suc(Box<Raw>),
    /// $\mathsf{rec}_\mathbb{N}\, P\, z\, s\, n$ -- $\mathbb{N}$-eliminator.
    NatRec(Box<Raw>, Box<Raw>, Box<Raw>, Box<Raw>),
    /// $\mathbb{B}$ -- booleans.
    Bool,
    /// $\mathsf{tt}$ -- the true bit.
    BTrue,
    /// $\mathsf{ff}$ -- the false bit.
    BFalse,
    /// $\mathsf{rec}_\mathbb{B}\, P\, t\, f\, b$ -- $\mathbb{B}$-eliminator.
    BoolRec(Box<Raw>, Box<Raw>, Box<Raw>, Box<Raw>),
    /// $\mathbb{1}$ -- the unit type.
    Unit,
    /// $\star$ -- the unique inhabitant of $\mathbb{1}$.
    TT,
    /// $\mathbb{0}$ -- the empty type.
    Empty,
    /// $\mathsf{rec}_\mathbb{0}\, P\, e$ -- ex falso.
    EmptyRec(Box<Raw>, Box<Raw>),
    /// $\mathsf{Eq}\, A\, x\, y$ -- observational equality (Pujet-Tabareau
    /// $x \sim_A y$), defined by recursion on $A$.
    Eq(Box<Raw>, Box<Raw>, Box<Raw>),
    /// $\mathsf{refl}$ -- reflexivity proof, inhabits $\mathsf{Eq}\, A\, a\, a$.
    Refl,
    /// $\mathsf{coe}\, A\, B\, e\, t$ -- coercion along $e : \mathsf{Eq}\,
    /// \mathcal{U}\, A\, B$ (Pujet-Tabareau write it $\mathsf{cast}$).
    Coe(Box<Raw>, Box<Raw>, Box<Raw>, Box<Raw>),
    /// $\mathsf{let}\, x : A := t\, \mathsf{in}\, u$.
    Let(Name, Box<Raw>, Box<Raw>, Box<Raw>),
    /// $t : A$ -- type annotation (turns checking into inference).
    Ann(Box<Raw>, Box<Raw>),
}

/// Core syntax: scope-resolved, sugar-free, de Bruijn indexed.
///
/// This is the $t, u, \ldots$ of Pujet-Tabareau Figure 2 (core MLTT)
/// plus the OTT extensions $\mathsf{Eq}$, $\mathsf{refl}$, $\mathsf{coe}$
/// of Figure 3.
#[derive(Clone, Debug)]
pub enum Tm {
    /// $x$ -- de Bruijn index $i$, referring to the $i$-th nearest binder.
    Var(Index),
    /// $\lambda x.\, t$.
    Lam(Name, Rc<Tm>),
    /// $t\, u$.
    App(Rc<Tm>, Rc<Tm>),
    /// $\Pi (x : A).\, B$.
    Pi(Name, Rc<Tm>, Rc<Tm>),
    /// $\Sigma (x : A).\, B$.
    Sigma(Name, Rc<Tm>, Rc<Tm>),
    /// $(a, b)$.
    Pair(Rc<Tm>, Rc<Tm>),
    /// $\pi_1\, t$.
    Fst(Rc<Tm>),
    /// $\pi_2\, t$.
    Snd(Rc<Tm>),
    /// $\mathcal{U}$ -- type-in-type universe (single level for simplicity).
    U,
    /// $\mathbb{N}$.
    Nat,
    /// $0 : \mathbb{N}$.
    Zero,
    /// $\mathsf{S}\, n$.
    Suc(Rc<Tm>),
    /// $\mathsf{rec}_\mathbb{N}\, P\, z\, s\, n$.
    NatRec(Rc<Tm>, Rc<Tm>, Rc<Tm>, Rc<Tm>),
    /// $\mathbb{B}$.
    Bool,
    /// $\mathsf{tt} : \mathbb{B}$.
    BTrue,
    /// $\mathsf{ff} : \mathbb{B}$.
    BFalse,
    /// $\mathsf{rec}_\mathbb{B}\, P\, t\, f\, b$.
    BoolRec(Rc<Tm>, Rc<Tm>, Rc<Tm>, Rc<Tm>),
    /// $\mathbb{1}$.
    Unit,
    /// $\star : \mathbb{1}$.
    TT,
    /// $\mathbb{0}$.
    Empty,
    /// $\mathsf{rec}_\mathbb{0}\, P\, e$.
    EmptyRec(Rc<Tm>, Rc<Tm>),
    /// $\mathsf{Eq}\, A\, x\, y$ -- Pujet-Tabareau $x \sim_A y$. The whole
    /// point of OTT: this *reduces* by recursion on $A$ rather than being
    /// inductively generated by $\mathsf{refl}$.
    Eq(Rc<Tm>, Rc<Tm>, Rc<Tm>),
    /// $\mathsf{refl}$ -- canonical inhabitant of $\mathsf{Eq}\, A\, a\, a$.
    Refl,
    /// $\mathsf{coe}\, A\, B\, e\, t$ -- transport along $e : \mathsf{Eq}\,
    /// \mathcal{U}\, A\, B$ (Pujet-Tabareau Figure 3 $\mathsf{cast}$).
    Coe(Rc<Tm>, Rc<Tm>, Rc<Tm>, Rc<Tm>),
    /// $\mathsf{let}\, x : A := t\, \mathsf{in}\, u$.
    Let(Name, Rc<Tm>, Rc<Tm>, Rc<Tm>),
}

/// Top-level declaration in an `.ott` file.
#[derive(Clone, Debug)]
pub enum Decl {
    /// `def f : A := t` -- introduces $f := t$ at type $A$ into the signature.
    Def(Name, Raw, Raw),
    /// `eval t` -- elaborate, normalize, and print the result.
    Eval(Raw),
    /// `check t : A` -- assert that $t$ checks at $A$.
    Check(Raw, Raw),
}

/// What the REPL grammar accepts on a single line.
#[derive(Clone, Debug)]
pub enum ReplInput {
    Decl(Decl),
    Term(Raw),
}
